package shim

import (
	"strings"
	"testing"

	"gotest.tools/v3/assert"
)

func TestTemplatesIncludeGeneratedHeader(t *testing.T) {
	tests := []struct {
		name     string
		template string
		want     []string
	}{
		{
			name:     "posix",
			template: posixTemplate,
			want: []string{
				"#!/bin/bash",
				"# Code generated by pocket; DO NOT EDIT.",
			},
		},
		{
			name:     "windows",
			template: windowsTemplate,
			want: []string{
				"@echo off",
				":: Code generated by pocket; DO NOT EDIT.",
			},
		},
		{
			name:     "powershell",
			template: powershellTemplate,
			want: []string{
				"# Code generated by pocket; DO NOT EDIT.",
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := strings.Split(tt.template, "\n")[:len(tt.want)]

			assert.DeepEqual(t, got, tt.want)
		})
	}
}
