# Code generated by pocket; DO NOT EDIT.
$ErrorActionPreference = "Stop"

# Resolve shim directory to find .pocket
$ShimDir = Split-Path -Parent $MyInvocation.MyCommand.Path

$PocketDir = Join-Path $ShimDir ".pocket"
$TaskScope = "."
$GoVersion = "1.26.5"
$GoInstallDir = "$PocketDir\tools\go\$GoVersion"
$GoBin = "$GoInstallDir\go\bin\go.exe"

# Expected checksums for each platform.
$Checksums = @{
    "aix-ppc64" = "e7f3c518fd7a8bc17f4389e342554016785f95ce447f8f09a260328de0d0f06c"
    "darwin-amd64" = "6231d8d3b8f5552ec6cbf6d685bdd5482e1e703214b120e89b3bf0d7bf1ef725"
    "darwin-arm64" = "efb87ff28af9a188d0536ef5d42e63dd52ba8263cd7344a993cc48dd11dedb6a"
    "dragonfly-amd64" = "96b53091297bd3a9ec8ed39f5f76b074c813dd74a6f429c03c667877ff27fdf8"
    "freebsd-386" = "1a0226fc025d97d30a112ad0d09b13dcacedc5b24b04bf8f21a0cd29aac4d947"
    "freebsd-amd64" = "0e5ddc51a62018211d461d6bf409939b04eaa4d6dd6d7097910090ef755ed947"
    "freebsd-arm" = "f8a59e86427158d89b2ba158d7f6004881e378fa3d7e4aefd4df17e4ee3a6bd1"
    "freebsd-arm64" = "ae3825c8c57cc0e64c2233bfb9bba2e091f2126728e4c33492592c24b60dfcd0"
    "illumos-amd64" = "fcd06289bd8a5a9962e5acab2f30e7daa74952327b01366fa9f6e07007e65be1"
    "linux-386" = "88c162b204e6eefcc32499453b492e80209f4a4c78c33092636901c540fb0d05"
    "linux-amd64" = "5c2c3b16caefa1d968a94c1daca04a7ca301a496d9b086e17ad77bb81393f053"
    "linux-arm64" = "fe4789e92b1f33358680864bbe8704289e7bb5fc207d80623c308935bd696d49"
    "linux-armv6l" = "6dae9edab81c13bccf962dec15f1fd2ec26c14a6821b4d2c92dab4130c289d7a"
    "linux-loong64" = "82736bb7794547a73372ddfeb1b370cfea4d17f04782a65e82a389a01ff0f7aa"
    "linux-mips" = "3d313aefb8b7547beae18bb69febcf1571f775146209332a48a2942993655417"
    "linux-mips64" = "7e5547e99a891e338fa5490b72d46ea7fd0593259df51561d7f55d4698503a8c"
    "linux-mips64le" = "7e05aceb9dea6033bc2f6dde29139293d8247cc2db749a206472b3916b1765a1"
    "linux-mipsle" = "e481470951e3a22a014ee70aebaae0c35aae4193a253d22ecf59d58f4bdbc450"
    "linux-ppc64" = "8ef02abd6f2b4040b7eb001b64597d16b9fa9aa563baaecf181ad8d9806c9991"
    "linux-ppc64le" = "c5d60e2b303bb612f20cd82786594b64874e73b35134025e27d3390bf284ae43"
    "linux-riscv64" = "d4a24dd4484d3f86b99c2d300af0dea5d184557e6d61eb7aba19ff61662750e3"
    "linux-s390x" = "09ce3c504c0323968b75a717244dca4f25cd4cf0443e5ff6bc0bfa74add89fa7"
    "netbsd-386" = "6df082b6dd877c3e71af3c44e67b8684f8592cb0fc50aed3ea9e58968bc3165f"
    "netbsd-amd64" = "daed1cb730d52e8b40866253b6271fd215f6128372dccc61d7784d4d3fb4a1bf"
    "netbsd-arm" = "d8a18f2d5afb6aaf47b79135221a964c21ee5cf5d568301a718904d887b1c96f"
    "netbsd-arm64" = "60520191abd288fb0f22b279ee63497b3a81318134e41f2bb80f548c9227bd6a"
    "openbsd-386" = "723a35e81882ddd8bdcb2539111f53ab4b03d4dbc114a2420d47963163465843"
    "openbsd-amd64" = "27721c64efcb571ecfbf52ee77f133ec73dca96015b315199be104ed2dfafd87"
    "openbsd-arm" = "2de3fb692c74c68a40d8c92ec6a077a18c14a44e8e41a8c22edeb286b3a4dfce"
    "openbsd-arm64" = "969a90bc34bda3ec06c0c3278ae00cdaa9b747b100cadec9f3f8c2cb36f01c69"
    "openbsd-ppc64" = "cb3908dd5904df453ebce07cfc660b7a14b7fed9525463521f01a04affd49eb8"
    "openbsd-riscv64" = "922864dbcb3ec989f456b2c313a46a4c0b0bd93b398603dc0db2d5a72b5ca47c"
    "plan9-386" = "7858fe6515a8e71050a3b59211b6c6f6947822497ecbe1ab81f4e4503b67a635"
    "plan9-amd64" = "513acf2518947e51210772145436e62eb67cc44738c5df3b6218dfeb66f6416c"
    "plan9-arm" = "131c06ed5b7ce904ff7b121c63ffd76a699fff43b96e019914f093ede1be9e4a"
    "solaris-amd64" = "33a1fc532f8d5fc5964b28a056729bc50a59657b653a5f1b04c2aeb2ac54c149"
    "windows-386" = "cab0f6847c17f4c904c0bacb6ec6b84e730fc797f4ba885f42383d580fc2d399"
    "windows-amd64" = "97e6b2a833b6d89f9ff17d25419ac0a7e3b482a044e9ab18cdef834bd834fd38"
    "windows-arm64" = "f96ee46396d69f1e231c8d981ec6a70216238a646a1f2cd74aea0d0016bbc017"
}

# Find Go binary.
$GoCmd = $null
if (Get-Command go -ErrorAction SilentlyContinue) {
    $GoCmd = "go"
} elseif (Test-Path $GoBin) {
    $GoCmd = $GoBin
} else {
    # Download Go.
    Write-Host "Go not found, downloading go$GoVersion..."

    $Arch = if ([Environment]::Is64BitOperatingSystem) { "amd64" } else { "386" }
    $Platform = "windows-$Arch"
    $ZipUrl = "https://go.dev/dl/go$GoVersion.windows-$Arch.zip"
    $ZipPath = "$env:TEMP\go$GoVersion.zip"

    New-Item -ItemType Directory -Force -Path $GoInstallDir | Out-Null
    Invoke-WebRequest -Uri $ZipUrl -OutFile $ZipPath

    # Verify checksum if available.
    $ExpectedHash = $Checksums[$Platform]
    if ($ExpectedHash) {
        $ActualHash = (Get-FileHash -Path $ZipPath -Algorithm SHA256).Hash.ToLower()
        if ($ActualHash -ne $ExpectedHash) {
            Remove-Item $ZipPath -Force
            Write-Error "Checksum verification failed!`nExpected: $ExpectedHash`nActual:   $ActualHash"
            exit 1
        }
        Write-Host "Checksum verified."
    } else {
        Write-Host "Warning: No checksum available for $Platform, skipping verification."
    }

    Expand-Archive -Path $ZipPath -DestinationPath $GoInstallDir -Force
    Remove-Item $ZipPath

    $GoCmd = $GoBin
    Write-Host "Go $GoVersion installed to $GoInstallDir"
}

$env:TASK_SCOPE = $TaskScope
& $GoCmd run -C $PocketDir . @args
exit $LASTEXITCODE
