// Code generated by pocket. DO NOT EDIT.
// To configure tasks, edit Config in config.go.
// See: https://github.com/fredrikaverpil/pocket#configuration

package main

import "github.com/fredrikaverpil/pocket/pk"

func main() {
	pk.RunMain(Config)
}
