// Code generated by pocket. DO NOT EDIT.
// To add custom tasks, add them to Config.Tasks in config.go.
// See: https://github.com/fredrikaverpil/pocket#custom-tasks

package main

import (
	"os"

	"github.com/fredrikaverpil/pocket/tasks"
	"github.com/goyek/goyek/v3"
	"github.com/goyek/x/boot"
)

func main() {
	// Get the context from the shim (defaults to root).
	context := os.Getenv("POK_CONTEXT")
	if context == "" {
		context = "."
	}

	// Create tasks based on config.
	// Filtering for context is handled internally by tasks.New.
	t := tasks.New(Config, context)

	goyek.SetDefault(t.All)
	boot.Main()
}
