// Code generated by bld. DO NOT EDIT.
// To add custom tasks, add them to Config.Custom in config.go.
// See: https://github.com/fredrikaverpil/bld#custom-tasks

package main

import (
	"os"

	"github.com/fredrikaverpil/bld/tasks"
	"github.com/goyek/goyek/v3"
	"github.com/goyek/x/boot"
)

func main() {
	// Get the context from the shim (defaults to root).
	context := os.Getenv("BLD_CONTEXT")
	if context == "" {
		context = "."
	}

	// Filter config to only include modules and custom tasks for this context.
	cfg := Config.ForContext(context)

	// Create tasks based on filtered config.
	t := tasks.New(cfg)

	goyek.SetDefault(t.All)
	boot.Main()
}
