// Code generated by pocket. DO NOT EDIT.
// To configure tasks, edit Config.AutoRun and Config.ManualRun in config.go.
// See: https://github.com/fredrikaverpil/pocket#configuration

package main

import (
	"github.com/fredrikaverpil/pocket"
	// Import tasks to register scaffold.GenerateAll for built-in tasks.
	_ "github.com/fredrikaverpil/pocket/tasks"
)

func main() {
	pocket.RunConfig(Config)
}
